# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-06 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': '\u53cb\u94fe', 'verbose_name_plural': '\u53cb\u94fe'},
        ),
    ]
